// const words = [
//   {
//     n: 1,
//     w: "Ambiguous",
//     h: "अस्पष्ट / दुविधापूर्ण",
//     syns: ["Confusing", "Unclear", "Vague"],
//     exam: "CDS I 2026",
//   },
//   {
//     n: 2,
//     w: "Abated",
//     h: "कम होना / शांत होना",
//     syns: ["Reduced", "Mitigated", "Diminished"],
//     exam: "CDS 2026 / NDA 2011",
//   },
//   {
//     n: 3,
//     w: "Arduous",
//     h: "कठिन / श्रमसाध्य",
//     syns: ["Difficult", "Laborious", "Strenuous"],
//     exam: "CDS I 2026",
//   },
//   {
//     n: 4,
//     w: "Adorn",
//     h: "सजाना / अलंकृत करना",
//     syns: ["Decorate", "Embellish", "Ornament"],
//     exam: "NDA I 2026 / GD 2019",
//   },
//   {
//     n: 5,
//     w: "Apex",
//     h: "शिखर / चोटी",
//     syns: ["Pinnacle", "Peak", "Zenith"],
//     exam: "CGL Dec 2022",
//   },
//   {
//     n: 6,
//     w: "Adjust",
//     h: "समायोजित करना",
//     syns: ["Adapt", "Modify", "Regulate"],
//     exam: "CGL Aug 2021",
//   },
//   {
//     n: 7,
//     w: "Arid",
//     h: "सूखा / बंजर",
//     syns: ["Dry", "Parched", "Barren"],
//     exam: "CGL Apr 2022",
//   },
//   {
//     n: 8,
//     w: "Affluent",
//     h: "धनी / समृद्ध",
//     syns: ["Prosperous", "Wealthy", "Opulent"],
//     exam: "CGL 2020 / Steno 2023",
//   },
//   {
//     n: 9,
//     w: "Answer",
//     h: "उत्तर / जवाब",
//     syns: ["Reply", "Response", "Retort"],
//     exam: "CGL Dec 2022",
//   },
//   {
//     n: 10,
//     w: "Abort",
//     h: "काम बंद करना / रद्द करना",
//     syns: ["End", "Terminate", "Abandon"],
//     exam: "CGL Mar 2020",
//   },
//   {
//     n: 11,
//     w: "Amend",
//     h: "संशोधन करना / सुधारना",
//     syns: ["Rectify", "Revise", "Correct"],
//     exam: "CGL Dec 2022",
//   },
//   {
//     n: 12,
//     w: "Abolish",
//     h: "समाप्त करना / उन्मूलन",
//     syns: ["Eliminate", "Eradicate", "Annihilate"],
//     exam: "CHSL 2024 / CGL 2021",
//   },
//   {
//     n: 13,
//     w: "Abstain",
//     h: "परहेज करना / बचना",
//     syns: ["Refrain", "Forbear", "Desist"],
//     exam: "CGL Aug 2021",
//   },
//   {
//     n: 14,
//     w: "Apathy",
//     h: "उदासीनता / निष्क्रियता",
//     syns: ["Indifference", "Lethargy", "Torpor"],
//     exam: "CGL Jul 2023",
//   },
//   {
//     n: 15,
//     w: "Advise",
//     h: "सलाह देना / परामर्श",
//     syns: ["Prescribe", "Counsel", "Guide"],
//     exam: "CGL Mar 2023 Tier-2",
//   },
//   {
//     n: 16,
//     w: "Adulterate",
//     h: "मिलावट करना",
//     syns: ["Contaminate", "Corrupt", "Pollute"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 17,
//     w: "Abrogate",
//     h: "रद्द करना / निरस्त करना",
//     syns: ["Repeal", "Revoke", "Rescind"],
//     exam: "CHSL Jun 2022",
//   },
//   {
//     n: 18,
//     w: "Aptitude",
//     h: "योग्यता / प्रतिभा",
//     syns: ["Talent", "Flair", "Knack"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 19,
//     w: "Advocate",
//     h: "वकील / समर्थन करना",
//     syns: ["Support", "Champion", "Endorse"],
//     exam: "MTS Jun 2023",
//   },
//   {
//     n: 20,
//     w: "Accolade",
//     h: "पुरस्कार / सम्मान",
//     syns: ["Praise", "Honor", "Commendation"],
//     exam: "MTS Jun 2023",
//   },
//   {
//     n: 21,
//     w: "Absolute",
//     h: "पूर्ण / संपूर्ण",
//     syns: ["Complete", "Total", "Utter"],
//     exam: "CHSL Aug 2021",
//   },
//   {
//     n: 22,
//     w: "Amazed",
//     h: "चकित / हैरान",
//     syns: ["Astonished", "Astounded", "Stunned"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 23,
//     w: "Advantage",
//     h: "लाभ / फायदा",
//     syns: ["Boon", "Benefit", "Asset"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 24,
//     w: "Autonomous",
//     h: "स्वायत्त / स्वतंत्र",
//     syns: ["Independent", "Sovereign", "Self-governing"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 25,
//     w: "Assail",
//     h: "हमला करना / आक्रमण",
//     syns: ["Attack", "Assault", "Besiege"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 26,
//     w: "Ability",
//     h: "क्षमता / योग्यता",
//     syns: ["Skill", "Competence", "Capability"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 27,
//     w: "Allege",
//     h: "आरोप लगाना / दावा करना",
//     syns: ["Charge", "Accuse", "Contend"],
//     exam: "CHSL Aug 2021",
//   },
//   {
//     n: 28,
//     w: "Appalling",
//     h: "भयानक / चौंकाने वाला",
//     syns: ["Shocking", "Horrifying", "Dreadful"],
//     exam: "CHSL Aug 2021",
//   },
//   {
//     n: 29,
//     w: "Announce",
//     h: "घोषणा करना",
//     syns: ["Advertise", "Declare", "Proclaim"],
//     exam: "CGL Dec 2022 / Jul 2023",
//   },
//   {
//     n: 30,
//     w: "Amass",
//     h: "इकट्ठा करना / जमा करना",
//     syns: ["Gather", "Accumulate", "Stockpile"],
//     exam: "CGL Apr 2022",
//   },
//   {
//     n: 31,
//     w: "Avert",
//     h: "टालना / रोकना",
//     syns: ["Prevent", "Avoid", "Forestall"],
//     exam: "CGL Apr 2022",
//   },
//   {
//     n: 32,
//     w: "Audacious",
//     h: "साहसी / निडर",
//     syns: ["Brave", "Bold", "Daring"],
//     exam: "Steno 2022 / NDA 2026",
//   },
//   {
//     n: 33,
//     w: "Abridge",
//     h: "संक्षिप्त करना / छोटा करना",
//     syns: ["Shorten", "Curtail", "Condense"],
//     exam: "CPO Nov 2022",
//   },
//   {
//     n: 34,
//     w: "Amalgam",
//     h: "मिश्रण / मिश्र धातु",
//     syns: ["Mixture", "Blend", "Combination"],
//     exam: "GD Dec 2021",
//   },
//   {
//     n: 35,
//     w: "Arrogant",
//     h: "अहंकारी / घमंडी",
//     syns: ["Haughty", "Insolent", "Conceited"],
//     exam: "GD Feb 2023",
//   },
//   {
//     n: 36,
//     w: "Aloof",
//     h: "अलग / दूर रहने वाला",
//     syns: ["Detached", "Reserved", "Distant"],
//     exam: "CPO Dec 2019",
//   },
//   {
//     n: 37,
//     w: "Addicted",
//     h: "आदी / लत लगी होना",
//     syns: ["Inclined", "Hooked", "Habituated"],
//     exam: "CPO Nov 2022",
//   },
//   {
//     n: 38,
//     w: "Aggregate",
//     h: "कुल / योग / समग्र",
//     syns: ["Total", "Sum", "Collective"],
//     exam: "GD Dec 2021",
//   },
//   {
//     n: 39,
//     w: "Adroit",
//     h: "कुशल / निपुण / दक्ष",
//     syns: ["Skilful", "Adept", "Dexterous"],
//     exam: "CPO May 2019",
//   },
//   {
//     n: 40,
//     w: "Adversary",
//     h: "प्रतिद्वंद्वी / शत्रु",
//     syns: ["Opponent", "Rival", "Foe"],
//     exam: "GD Dec 2021",
//   },
//   {
//     n: 41,
//     w: "Alter",
//     h: "बदलना / परिवर्तित करना",
//     syns: ["Transform", "Modify", "Change"],
//     exam: "GD Dec 2021",
//   },
//   {
//     n: 42,
//     w: "Apprehension",
//     h: "भय / आशंका / चिंता",
//     syns: ["Fear", "Anxiety", "Trepidation"],
//     exam: "Steno Oct 2023",
//   },
//   {
//     n: 43,
//     w: "Amusing",
//     h: "मनोरंजक / दिलचस्प",
//     syns: ["Laughable", "Entertaining", "Comic"],
//     exam: "GD Nov 2021",
//   },
//   {
//     n: 44,
//     w: "Aim",
//     h: "लक्ष्य / उद्देश्य",
//     syns: ["Purpose", "Goal", "Objective"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 45,
//     w: "Allow",
//     h: "अनुमति देना",
//     syns: ["Permit", "Authorize", "Sanction"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 46,
//     w: "Annoy",
//     h: "परेशान करना / चिढ़ाना",
//     syns: ["Vex", "Irritate", "Irk"],
//     exam: "GD Jan 2023",
//   },
//   {
//     n: 47,
//     w: "Active",
//     h: "सक्रिय / फुर्तीला",
//     syns: ["Busy", "Energetic", "Lively"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 48,
//     w: "Auspicious",
//     h: "शुभ / अनुकूल",
//     syns: ["Fortunate", "Favorable", "Propitious"],
//     exam: "GD Jan 2023 / CPO 2020",
//   },
//   {
//     n: 49,
//     w: "Achieve",
//     h: "प्राप्त करना / हासिल करना",
//     syns: ["Succeed", "Accomplish", "Attain"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 50,
//     w: "Alight",
//     h: "उतरना / नीचे आना",
//     syns: ["Descend", "Dismount", "Land"],
//     exam: "GD Jan 2023",
//   },
//   {
//     n: 51,
//     w: "Attain",
//     h: "प्राप्त करना / पाना",
//     syns: ["Achieve", "Accomplish", "Obtain"],
//     exam: "GD Feb 2023",
//   },
//   {
//     n: 52,
//     w: "Accept",
//     h: "स्वीकार करना",
//     syns: ["Agree", "Consent", "Approve"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 53,
//     w: "Assume",
//     h: "मान लेना / अनुमान करना",
//     syns: ["Think", "Presume", "Suppose"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 54,
//     w: "Alert",
//     h: "सतर्क / चौकस",
//     syns: ["Vigilant", "Watchful", "Wary"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 55,
//     w: "Attire",
//     h: "वस्त्र / पहनावा",
//     syns: ["Dress", "Garb", "Apparel"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 56,
//     w: "Abscond",
//     h: "फरार हो जाना / भाग जाना",
//     syns: ["Flee", "Run away", "Escape"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 57,
//     w: "Ascend",
//     h: "चढ़ना / ऊपर जाना",
//     syns: ["Climb", "Mount", "Scale"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 58,
//     w: "Abnegate",
//     h: "त्याग करना / इनकार करना",
//     syns: ["Renounce", "Relinquish", "Forsake"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 59,
//     w: "Avoid",
//     h: "बचना / टालना",
//     syns: ["Evade", "Dodge", "Shun"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 60,
//     w: "Affirmative",
//     h: "सकारात्मक / हाँ में",
//     syns: ["Positive", "Confirmatory", "Assertive"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 61,
//     w: "Affiliated",
//     h: "संबद्ध / जुड़ा हुआ",
//     syns: ["Allied", "Associated", "Connected"],
//     exam: "CGL 2024",
//   },
//   {
//     n: 62,
//     w: "Accustomed",
//     h: "अभ्यस्त / आदी",
//     syns: ["Habituated", "Used to", "Familiar"],
//     exam: "Steno Dec 2020",
//   },
//   {
//     n: 63,
//     w: "Affirm",
//     h: "पुष्टि करना / दृढ़ता से कहना",
//     syns: ["Confirm", "Assert", "Declare"],
//     exam: "CHSL Tier-1 2024",
//   },
//   {
//     n: 64,
//     w: "Acne",
//     h: "मुंहासे / त्वचा विकार",
//     syns: ["Pimples", "Blemishes", "Spots"],
//     exam: "DP HCM Jan 2026",
//   },
//   {
//     n: 65,
//     w: "Alluded",
//     h: "संकेत करना / इशारा",
//     syns: ["Mentioned Indirectly", "Hinted", "Referred"],
//     exam: "DP HCM Jan 2026",
//   },
//   {
//     n: 66,
//     w: "Aghast",
//     h: "भौचक्का / स्तब्ध",
//     syns: ["Horrified", "Shocked", "Appalled"],
//     exam: "CDS 2020",
//   },
//   {
//     n: 67,
//     w: "Akin",
//     h: "समान / मिलता-जुलता",
//     syns: ["Similar", "Alike", "Analogous"],
//     exam: "CDS 2019",
//   },
//   {
//     n: 68,
//     w: "Advise",
//     h: "सलाह देना",
//     syns: ["Counsel", "Guide", "Recommend"],
//     exam: "Rajasthan HC 2018-19",
//   },
//   {
//     n: 69,
//     w: "Applaud",
//     h: "तालियाँ बजाना / प्रशंसा",
//     syns: ["Praise", "Acclaim", "Commend"],
//     exam: "KVS PRT Feb 2023",
//   },
//   {
//     n: 70,
//     w: "Apogee",
//     h: "उच्चतम बिंदु / शिखर",
//     syns: ["Peak", "Pinnacle", "Zenith"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 71,
//     w: "Assiduous",
//     h: "परिश्रमी / लगनशील",
//     syns: ["Diligent", "Industrious", "Tireless"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 72,
//     w: "Aggressive",
//     h: "आक्रामक / उग्र",
//     syns: ["Hostile", "Belligerent", "Militant"],
//     exam: "ACIO Feb 2021",
//   },
//   {
//     n: 73,
//     w: "Amity",
//     h: "मित्रता / सौहार्द",
//     syns: ["Friendship", "Goodwill", "Harmony"],
//     exam: "NDA & NA Sep 2014",
//   },
//   {
//     n: 74,
//     w: "Age",
//     h: "युग / काल / दौर",
//     syns: ["Era", "Epoch", "Period"],
//     exam: "NDA & NA Apr 2013",
//   },
//   {
//     n: 75,
//     w: "Access",
//     h: "पहुँच / प्रवेश",
//     syns: ["Reach", "Approach", "Entry"],
//     exam: "DSSSB 2014",
//   },
//   {
//     n: 76,
//     w: "Abyss",
//     h: "गहरी खाई / अथाह गहराई",
//     syns: ["Deep Pit", "Chasm", "Gorge"],
//     exam: "NDA & NA Apr 2010",
//   },
//   {
//     n: 77,
//     w: "Annual",
//     h: "वार्षिक / साल में एक बार",
//     syns: ["Yearly", "Per annum", "Periodic"],
//     exam: "CDS 2015",
//   },
//   {
//     n: 78,
//     w: "Ameliorate",
//     h: "सुधारना / बेहतर बनाना",
//     syns: ["Improve", "Enhance", "Better"],
//     exam: "DSSSB Jun 2017",
//   },
//   {
//     n: 79,
//     w: "Acquit",
//     h: "बरी करना / दोषमुक्त करना",
//     syns: ["Free", "Exonerate", "Clear"],
//     exam: "DSSSB Mar 2015",
//   },
//   {
//     n: 80,
//     w: "Alien",
//     h: "विदेशी / अजनबी / अपरिचित",
//     syns: ["Foreigner", "Stranger", "Outsider"],
//     exam: "DSSSB Aug 2019",
//   },
//   {
//     n: 81,
//     w: "Abnormal",
//     h: "असामान्य / विचित्र",
//     syns: ["Strange", "Unusual", "Aberrant"],
//     exam: "DSSSB Aug 2019",
//   },
//   {
//     n: 82,
//     w: "Assemble",
//     h: "इकट्ठा होना / जमा करना",
//     syns: ["Amass", "Gather", "Congregate"],
//     exam: "CHSL Oct 2020",
//   },
//   {
//     n: 83,
//     w: "Abrupt",
//     h: "अचानक / अप्रत्याशित",
//     syns: ["Sudden", "Hasty", "Unexpected"],
//     exam: "MTS Oct 2017",
//   },
//   {
//     n: 84,
//     w: "Acclaim",
//     h: "प्रशंसा करना / जय-जयकार",
//     syns: ["Praise", "Laud", "Applaud"],
//     exam: "MTS Aug 2019",
//   },
//   {
//     n: 85,
//     w: "Amicable",
//     h: "मैत्रीपूर्ण / सौहार्दपूर्ण",
//     syns: ["Friendly", "Cordial", "Amiable"],
//     exam: "DSSSB 2015 / CHSL 2023",
//   },
//   {
//     n: 86,
//     w: "Antique",
//     h: "प्राचीन / पुराना",
//     syns: ["Ancient", "Archaic", "Old"],
//     exam: "MTS 2024 / CHSL 2024",
//   },
//   {
//     n: 87,
//     w: "Abandon",
//     h: "छोड़ देना / त्यागना",
//     syns: ["Quit", "Forsake", "Desert"],
//     exam: "CGL 2022 / CPO 2023",
//   },
//   {
//     n: 88,
//     w: "Adversity",
//     h: "विपत्ति / मुसीबत",
//     syns: ["Misfortune", "Hardship", "Calamity"],
//     exam: "GD Jan 2023 / CGL 2024",
//   },
//   {
//     n: 89,
//     w: "Adept",
//     h: "कुशल / दक्ष / माहिर",
//     syns: ["Expert", "Proficient", "Skilled"],
//     exam: "DSSSB 2014 / CGL 2019",
//   },
//   {
//     n: 90,
//     w: "Absurd",
//     h: "बेतुका / हास्यास्पद",
//     syns: ["Ridiculous", "Illogical", "Preposterous"],
//     exam: "CPO Nov 2020 / CHSL 2024",
//   },
//   {
//     n: 91,
//     w: "Anxious",
//     h: "चिंतित / व्याकुल",
//     syns: ["Worried", "Uneasy", "Perturbed"],
//     exam: "NDA Nov 2019 / MTS Aug 2019",
//   },
//   {
//     n: 92,
//     w: "Ardent",
//     h: "उत्साही / जोशीला / प्रबल",
//     syns: ["Passionate", "Fervent", "Zealous"],
//     exam: "DSSSB 2022 / CPO 2024",
//   },
//   {
//     n: 93,
//     w: "Ample",
//     h: "पर्याप्त / भरपूर",
//     syns: ["Sufficient", "Abundant", "Plentiful"],
//     exam: "GD Jan 2023 / MTS Oct 2021",
//   },
//   {
//     n: 94,
//     w: "Alleviate",
//     h: "कम करना / राहत देना",
//     syns: ["Mitigate", "Relieve", "Lessen"],
//     exam: "CHSL 2024 / Steno 2021",
//   },
//   {
//     n: 95,
//     w: "Adequate",
//     h: "पर्याप्त / उचित",
//     syns: ["Sufficient", "Enough", "Satisfactory"],
//     exam: "Dec 2019 / Steno 2023 / CGL 2024",
//   },
//   {
//     n: 96,
//     w: "Awkward",
//     h: "अजीब / बेढंगा / अनाड़ी",
//     syns: ["Unskilful", "Clumsy", "Inept"],
//     exam: "GD Jan 2023 / MTS Aug 2019",
//   },
//   {
//     n: 97,
//     w: "Assist",
//     h: "सहायता करना / मदद करना",
//     syns: ["Help", "Aid", "Support"],
//     exam: "CGL Jun 2019 / GD Nov 2021",
//   },
//   {
//     n: 98,
//     w: "Abuse",
//     h: "दुरुपयोग / गाली देना",
//     syns: ["Harm", "Misuse", "Revile"],
//     exam: "MTS Oct 2021 / DSSSB 2022",
//   },
//   {
//     n: 99,
//     w: "Adamant",
//     h: "अडिग / हठी / जिद्दी",
//     syns: ["Stubborn", "Obstinate", "Inflexible"],
//     exam: "GD Jan 2023 / CGL Jul 2023",
//   },
//   {
//     n: 100,
//     w: "Adjourn",
//     h: "स्थगित करना",
//     syns: ["Postpone", "Defer", "Suspend"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 101,
//     w: "Agile",
//     h: "फुर्तीला / चपल / तेज",
//     syns: ["Nimble", "Spry", "Active"],
//     exam: "CHSL Oct 2020 / MTS Aug 2019",
//   },
//   {
//     n: 102,
//     w: "Appeal",
//     h: "अपील / आकर्षण / अनुरोध",
//     syns: ["Charm", "Attract", "Implore"],
//     exam: "GD Nov 2021",
//   },
//   {
//     n: 103,
//     w: "Abide",
//     h: "पालन करना / सहना",
//     syns: ["Comply", "Tolerate", "Obey"],
//     exam: "MTS 2024 / MTS May 2023",
//   },
//   {
//     n: 104,
//     w: "Absolve",
//     h: "दोषमुक्त करना",
//     syns: ["Pardon", "Exonerate", "Acquit"],
//     exam: "CGL Aug 2021",
//   },
//   {
//     n: 105,
//     w: "Anticipate",
//     h: "पहले से अनुमान लगाना",
//     syns: ["Predict", "Foresee", "Expect"],
//     exam: "CGL Dec 2022 / MTS 2024",
//   },
//   {
//     n: 106,
//     w: "Accumulate",
//     h: "जमा करना / संचित करना",
//     syns: ["Store", "Amass", "Collect"],
//     exam: "KVS PRT Feb 2023 / ACIO 2021",
//   },
//   {
//     n: 107,
//     w: "Appropriate",
//     h: "उचित / उपयुक्त / सही",
//     syns: ["Suitable", "Fitting", "Apt"],
//     exam: "NDA Sep 2016 / MTS May 2023",
//   },
//   {
//     n: 108,
//     w: "Arraign",
//     h: "अभियोग लगाना / आरोपी बनाना",
//     syns: ["Prosecute", "Indict", "Charge"],
//     exam: "CHSL May 2022",
//   },
//   {
//     n: 109,
//     w: "Artful",
//     h: "चालाक / चतुर / कुटिल",
//     syns: ["Crafty", "Cunning", "Clever"],
//     exam: "MTS Jul 2022 / MTS Aug 2019",
//   },
//   {
//     n: 110,
//     w: "Assassinate",
//     h: "राजनीतिक हत्या करना",
//     syns: ["Murder", "Slay", "Kill"],
//     exam: "CHSL May 2022",
//   },
//   {
//     n: 111,
//     w: "Assent",
//     h: "सहमति देना / अनुमोदन",
//     syns: ["Agree", "Consent", "Concur"],
//     exam: "KVS PRT Feb 2023 / NDA 2019",
//   },
//   {
//     n: 112,
//     w: "Aroma",
//     h: "सुगंध / खुशबू",
//     syns: ["Scent", "Fragrance", "Odour"],
//     exam: "MTS Aug 2019 / GD Dec 2021",
//   },
//   {
//     n: 113,
//     w: "Attributed",
//     h: "आरोपित / जिम्मेदार ठहराना",
//     syns: ["Ascribed", "Credited", "Imputed"],
//     exam: "CDS 2019 / CGL Jun 2019 / MTS Aug 2019",
//   },
//   {
//     n: 114,
//     w: "Abhor",
//     h: "घृणा करना / नफरत करना",
//     syns: ["Detest", "Loathe", "Despise"],
//     exam: "NDA/CDS",
//   },
//   {
//     n: 115,
//     w: "Abortive",
//     h: "असफल / निष्फल / व्यर्थ",
//     syns: ["Unsuccessful", "Futile", "Vain"],
//     exam: "SSC/NDA",
//   },
//   {
//     n: 116,
//     w: "Abash",
//     h: "शर्मिंदा करना / झेंपाना",
//     syns: ["Embarrass", "Disconcert", "Humble"],
//     exam: "SSC GD",
//   },
//   {
//     n: 117,
//     w: "Acrid",
//     h: "तीखा / कड़वा / चुभने वाला",
//     syns: ["Harsh", "Pungent", "Bitter"],
//     exam: "SSC MTS",
//   },
//   {
//     n: 118,
//     w: "Admonish",
//     h: "चेतावनी देना / सावधान करना",
//     syns: ["Warn", "Caution", "Reprimand"],
//     exam: "NDA/KVS",
//   },
//   {
//     n: 119,
//     w: "Adulation",
//     h: "चापलूसी / झूठी तारीफ",
//     syns: ["Flattery", "Sycophancy", "Fawning"],
//     exam: "SSC/CDS",
//   },
//   {
//     n: 120,
//     w: "Ambience",
//     h: "माहौल / वातावरण / परिवेश",
//     syns: ["Atmosphere", "Environment", "Milieu"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 121,
//     w: "Alloy",
//     h: "मिश्र धातु / संयोजन",
//     syns: ["Combination", "Mixture", "Blend"],
//     exam: "SSC MTS",
//   },
//   {
//     n: 122,
//     w: "Adage",
//     h: "कहावत / लोकोक्ति",
//     syns: ["Proverb", "Maxim", "Saying"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 123,
//     w: "Abstruse",
//     h: "कठिन / दुरूह / जटिल",
//     syns: ["Recondite", "Obscure", "Arcane"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 124,
//     w: "Affectation",
//     h: "दिखावा / बनावट / ढोंग",
//     syns: ["Pretension", "Pose", "Mannerism"],
//     exam: "SSC/CDS",
//   },
//   {
//     n: 125,
//     w: "Axiom",
//     h: "स्वयंसिद्ध सत्य / सिद्धांत",
//     syns: ["Truth", "Maxim", "Principle"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 126,
//     w: "Avarice",
//     h: "लालच / लोभ / धन की भूख",
//     syns: ["Greed", "Covetousness", "Cupidity"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 127,
//     w: "Auspicious",
//     h: "शुभ / अनुकूल / फायदेमंद",
//     syns: ["Favorable", "Propitious", "Fortunate"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 128,
//     w: "Augment",
//     h: "बढ़ाना / वृद्धि करना",
//     syns: ["Increase", "Enhance", "Amplify"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 129,
//     w: "Appreciate",
//     h: "सराहना करना / कद्र करना",
//     syns: ["Value", "Cherish", "Esteem"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 130,
//     w: "Apocryphal",
//     h: "संदिग्ध / असत्य / नकली",
//     syns: ["Fictitious", "Dubious", "Spurious"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 131,
//     w: "Aptitude",
//     h: "योग्यता / क्षमता",
//     syns: ["Ability", "Talent", "Competence"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 132,
//     w: "Arbiter",
//     h: "मध्यस्थ / निर्णायक",
//     syns: ["Judge", "Mediator", "Arbitrator"],
//     exam: "SSC CGL/CPO",
//   },
//   {
//     n: 133,
//     w: "Assuage",
//     h: "शांत करना / राहत देना",
//     syns: ["Pacify", "Mollify", "Appease"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 134,
//     w: "Attrition",
//     h: "क्षय / घटाव / कमी",
//     syns: ["Weakening", "Erosion", "Diminution"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 135,
//     w: "Ascetic",
//     h: "तपस्वी / सन्यासी / वैरागी",
//     syns: ["Saint", "Monk", "Abstinent"],
//     exam: "SSC CGL/CHSL",
//   },
//   {
//     n: 136,
//     w: "Apocalypse",
//     h: "प्रलय / महाविनाश",
//     syns: ["Devastation", "Catastrophe", "Calamity"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 137,
//     w: "Antithesis",
//     h: "विरोध / विपरीत / उलटा",
//     syns: ["Opposite", "Contradiction", "Contrast"],
//     exam: "SSC CGL",
//   },
//   {
//     n: 138,
//     w: "Anger",
//     h: "क्रोध / गुस्सा / रोष",
//     syns: ["Fury", "Rage", "Wrath"],
//     exam: "CGL Dec 2022",
//   },
//   {
//     n: 139,
//     w: "Amusement",
//     h: "मनोरंजन / आनंद / ख़ुशी",
//     syns: ["Pleasure", "Entertainment", "Delight"],
//     exam: "CGL Apr 2022",
//   },
//   {
//     n: 140,
//     w: "Accurately",
//     h: "सटीकता से / सही ढंग से",
//     syns: ["Correctly", "Precisely", "Exactly"],
//     exam: "CGL Nov 2020 Tier-2",
//   },
//   {
//     n: 141,
//     w: "Affront",
//     h: "अपमान / अनादर",
//     syns: ["Insult", "Offend", "Humiliate"],
//     exam: "CHSL Jun 2022",
//   },
//   {
//     n: 142,
//     w: "Allay",
//     h: "शांत करना / कम करना",
//     syns: ["Relieve", "Mitigate", "Soothe"],
//     exam: "CHSL Jun 2022",
//   },
//   {
//     n: 143,
//     w: "Advent",
//     h: "आगमन / आना",
//     syns: ["Arrival", "Coming", "Appearance"],
//     exam: "MTS Jul 2022",
//   },
//   {
//     n: 144,
//     w: "Abominable",
//     h: "घृणित / जघन्य / भयानक",
//     syns: ["Obnoxious", "Loathsome", "Detestable"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 145,
//     w: "Astute",
//     h: "चालाक / तीक्ष्ण बुद्धि",
//     syns: ["Shrewd", "Clever", "Canny"],
//     exam: "MTS Jul 2022",
//   },
//   {
//     n: 146,
//     w: "Anxiety",
//     h: "चिंता / घबराहट",
//     syns: ["Worry", "Apprehension", "Unease"],
//     exam: "CHSL Tier-1 2024 / MTS Oct 2021",
//   },
//   {
//     n: 147,
//     w: "Alarm",
//     h: "घबराहट / भय / सतर्कता",
//     syns: ["Panic", "Fright", "Dread"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 148,
//     w: "Agony",
//     h: "पीड़ा / तकलीफ / वेदना",
//     syns: ["Pain", "Anguish", "Torment"],
//     exam: "MTS Oct 2021",
//   },
//   {
//     n: 149,
//     w: "Allude",
//     h: "संकेत करना / इशारा करना",
//     syns: ["Refer", "Hint", "Suggest"],
//     exam: "GD Jan 2023",
//   },
//   {
//     n: 150,
//     w: "Afflicted",
//     h: "पीड़ित / ग्रस्त",
//     syns: ["Distressed", "Tormented", "Troubled"],
//     exam: "CPO Dec 2019",
//   },
//   {
//     n: 151,
//     w: "Abound",
//     h: "प्रचुर मात्रा में होना",
//     syns: ["Flourish", "Increase", "Multiply"],
//     exam: "CGL Jul 2023",
//   },
//   {
//     n: 152,
//     w: "Absorbed",
//     h: "मग्न / तल्लीन",
//     syns: ["Preoccupied", "Engrossed", "Soaked"],
//     exam: "CGL Jul 2023",
//   },
//   {
//     n: 153,
//     w: "Acknowledgement",
//     h: "स्वीकृति / पुष्टि",
//     syns: ["Confirmation", "Recognition", "Acceptance"],
//     exam: "CGL Mar 2020",
//   },
//   {
//     n: 154,
//     w: "Assuagement",
//     h: "शांत करना / राहत",
//     syns: ["Mollification", "Relief", "Pacification"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 155,
//     w: "Ambitious",
//     h: "महत्वाकांक्षी",
//     syns: ["Aspiring", "Driven", "Determined"],
//     exam: "CHSL Aug 2023",
//   },
//   {
//     n: 156,
//     w: "Apologetic",
//     h: "पश्चातापपूर्ण",
//     syns: ["Contrite", "Regretful", "Sorry"],
//     exam: "CHSL Mar 2023",
//   },
//   {
//     n: 157,
//     w: "Amble",
//     h: "धीरे-धीरे चलना",
//     syns: ["Wander", "Stroll", "Roam"],
//     exam: "CHSL May 2022",
//   },
//   {
//     n: 158,
//     w: "Apathetic",
//     h: "उदासीन",
//     syns: ["Indifferent", "Unconcerned", "Passive"],
//     exam: "CHSL Aug 2021",
//   },
//   {
//     n: 159,
//     w: "Ancient",
//     h: "प्राचीन",
//     syns: ["Antique", "Old", "Archaic"],
//     exam: "MTS Sep 2023",
//   },
//   {
//     n: 160,
//     w: "Attack",
//     h: "आक्रमण करना",
//     syns: ["Assault", "Strike", "Raid"],
//     exam: "MTS May 2023",
//   },
//   {
//     n: 161,
//     w: "Appeased",
//     h: "शांत किया हुआ",
//     syns: ["Pacified", "Calmed", "Satisfied"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 162,
//     w: "Admonition",
//     h: "चेतावनी",
//     syns: ["Counsel", "Warning", "Advice"],
//     exam: "SSC GD Jan 2023",
//   },
//   {
//     n: 163,
//     w: "Acquired",
//     h: "प्राप्त किया हुआ",
//     syns: ["Obtained", "Gained", "Earned"],
//     exam: "SSC GD Jan 2023",
//   },
//   {
//     n: 164,
//     w: "Admitted",
//     h: "स्वीकार किया हुआ",
//     syns: ["Acknowledged", "Accepted", "Confessed"],
//     exam: "SSC GD Jan 2023",
//   },
//   {
//     n: 165,
//     w: "Affliction",
//     h: "कष्ट / पीड़ा",
//     syns: ["Bane", "Suffering", "Misery"],
//     exam: "SSC GD Jan 2023",
//   },
//   {
//     n: 166,
//     w: "Annoyance",
//     h: "झुंझलाहट",
//     syns: ["Anger", "Irritation", "Vexation"],
//     exam: "SSC GD Jan 2023",
//   },
//   {
//     n: 167,
//     w: "Antagonist",
//     h: "विरोधी",
//     syns: ["Adversary", "Opponent", "Enemy"],
//     exam: "SSC GD Feb 2023",
//   },
//   {
//     n: 168,
//     w: "Accomplish",
//     h: "पूरा करना",
//     syns: ["Achieve", "Complete", "Perform"],
//     exam: "SSC GD Feb 2023",
//   },
//   {
//     n: 169,
//     w: "Absolutely",
//     h: "पूर्णतः",
//     syns: ["Definitely", "Completely", "Entirely"],
//     exam: "SSC GD Dec 2021",
//   },
//   {
//     n: 170,
//     w: "Application",
//     h: "अनुप्रयोग / आवेदन",
//     syns: ["Implementation", "Use", "Execution"],
//     exam: "CPO Nov 2022",
//   },
//   {
//     n: 171,
//     w: "Accredit",
//     h: "मान्यता देना",
//     syns: ["Certify", "Authorize", "Approve"],
//     exam: "CPO Nov 2022",
//   },
//   {
//     n: 172,
//     w: "Applause",
//     h: "तालियाँ / प्रशंसा",
//     syns: ["Approval", "Praise", "Acclaim"],
//     exam: "CPO 2019",
//   },
//   {
//     n: 173,
//     w: "Acquisitive",
//     h: "लालची / पाने की इच्छा रखने वाला",
//     syns: ["Eager", "Greedy", "Aspirational"],
//     exam: "Steno Oct 2023",
//   },
//   {
//     n: 174,
//     w: "Anguish",
//     h: "पीड़ा",
//     syns: ["Pain", "Agony", "Torment"],
//     exam: "Steno Oct 2023",
//   },
//   {
//     n: 175,
//     w: "Aplomb",
//     h: "आत्मविश्वास",
//     syns: ["Self-assurance", "Confidence", "Composure"],
//     exam: "Steno Nov 2022",
//   },
//   {
//     n: 176,
//     w: "Astonish",
//     h: "चकित करना",
//     syns: ["Surprise", "Amaze", "Astound"],
//     exam: "Steno Nov 2021",
//   },
//   {
//     n: 177,
//     w: "Altruistic",
//     h: "परोपकारी",
//     syns: ["Philanthropic", "Selfless", "Generous"],
//     exam: "CGL 2024",
//   },
//   {
//     n: 178,
//     w: "Ambition",
//     h: "महत्वाकांक्षा",
//     syns: ["Eagerness", "Aspiration", "Goal"],
//     exam: "CGL 2024",
//   },
//   {
//     n: 179,
//     w: "Advanced",
//     h: "उन्नत / आधुनिक",
//     syns: ["Modern", "Developed", "Progressive"],
//     exam: "CHSL 2024",
//   },
//   {
//     n: 180,
//     w: "Appalled",
//     h: "स्तब्ध / घृणा से भर जाना",
//     syns: ["Disgusted", "Horrified", "Shocked"],
//     exam: "CHSL 2024",
//   },
//   {
//     n: 181,
//     w: "Ablaze",
//     h: "जलता हुआ",
//     syns: ["Burning", "Flaming", "On fire"],
//     exam: "CHSL 2024",
//   },
//   {
//     n: 182,
//     w: "Agreed",
//     h: "सहमत",
//     syns: ["Supported", "Accepted", "Approved"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 183,
//     w: "Averted",
//     h: "टाल दिया गया",
//     syns: ["Avoided", "Prevented", "Evaded"],
//     exam: "MTS 2024",
//   },
//   {
//     n: 184,
//     w: "Astonished",
//     h: "हैरान",
//     syns: ["Stunned", "Surprised", "Amazed"],
//     exam: "CPO 2024",
//   },
//   {
//     n: 185,
//     w: "Anchorites",
//     h: "सन्यासी",
//     syns: ["Hermits", "Monks", "Recluses"],
//     exam: "Selection Post 2024",
//   },
//   {
//     n: 186,
//     w: "Awry",
//     h: "टेढ़ा / गलत",
//     syns: ["Askew", "Crooked", "Distorted"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 187,
//     w: "Asperity",
//     h: "कटुता",
//     syns: ["Harshness", "Severity", "Roughness"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 188,
//     w: "Anachronistic",
//     h: "पुराना / समय से बाहर",
//     syns: ["Outdated", "Old-fashioned", "Obsolete"],
//     exam: "CGL 2025",
//   },
//   {
//     n: 189,
//     w: "Adversely",
//     h: "हानिकारक रूप से",
//     syns: ["Detrimentally", "Negatively", "Badly"],
//     exam: "CHSL 2024",
//   },
//   {
//     n: 190,
//     w: "Acquiesce",
//     h: "सहमति देना",
//     syns: ["Concur", "Agree", "Consent"],
//     exam: "CGL 2024",
//   },
//   {
//     n: 191,
//     w: "Adoration",
//     h: "आराधना / प्रशंसा",
//     syns: ["Admiration", "Worship", "Love"],
//     exam: "KVS PRT 2023",
//   },
//   {
//     n: 192,
//     w: "Abhorrent",
//     h: "घृणित",
//     syns: ["Hateful", "Detestable", "Loathsome"],
//     exam: "KVS PRT 2023",
//   },
//   {
//     n: 193,
//     w: "Abode",
//     h: "निवास स्थान",
//     syns: ["Dwelling", "Residence", "Home"],
//     exam: "CHSL Apr 2021",
//   },
//   {
//     n: 194,
//     w: "Aversion",
//     h: "घृणा / विरोध",
//     syns: ["Hostility", "Dislike", "Antipathy"],
//     exam: "NDA 2021",
//   },
//   {
//     n: 195,
//     w: "Amorphous",
//     h: "आकारहीन",
//     syns: ["Nebulous", "Formless", "Shapeless"],
//     exam: "DSSSB 2021",
//   },
//   {
//     n: 196,
//     w: "Acumen",
//     h: "तीक्ष्ण बुद्धि",
//     syns: ["Ingenuity", "Sharpness", "Wisdom"],
//     exam: "DSSSB 2021",
//   },
//   {
//     n: 197,
//     w: "Ascertained",
//     h: "निश्चित किया गया",
//     syns: ["Determined", "Verified", "Confirmed"],
//     exam: "CDS 2020",
//   },
//   {
//     n: 198,
//     w: "Admit",
//     h: "स्वीकार करना",
//     syns: ["Accept", "Avow", "Acknowledge"],
//     exam: "CDS 2018",
//   },
//   {
//     n: 199,
//     w: "Aspire",
//     h: "आकांक्षा रखना",
//     syns: ["Hope", "Aim", "Desire"],
//     exam: "CDS 2014",
//   },
//   {
//     n: 200,
//     w: "Apprise",
//     h: "सूचित करना",
//     syns: ["Inform", "Notify", "Tell"],
//     exam: "CDS 2011",
//   },
// ];

let words = [];

async function loadWords(letter = "a") {
  try {
    const response = await fetch(`./vocabs/${letter}.json`);
    words = await response.json();

    renderCards(words);
  } catch (error) {
    console.error("Error loading JSON:", error);
  }
}

loadWords("a");

let currentFilter = "all";

function renderCards(data) {
  const grid = document.getElementById("grid");
  document.getElementById("count").textContent =
    `${data.length} word${data.length !== 1 ? "s" : ""}`;
  if (!data.length) {
    grid.innerHTML =
      '<div class="empty"><h3>No words found</h3><p>Try a different search or filter</p></div>';
    return;
  }
  grid.innerHTML = data
    .map(
      (d, i) => `
    <div class="card" style="animation-delay:${Math.min(i * 20, 300)}ms">
      <div class="card-header">
        <span class="num">${String(d.n).padStart(2, "0")}</span>
        <span class="word">${d.w}</span>
        ${d.exam ? `<span class="exam-tag">${d.exam.split(" ")[0]}</span>` : ""}
      </div>
      <div class="card-body">
        <div class="hindi-block">
          <div class="row-label">हिंदी अर्थ</div>
          <div class="hindi-text">${d.h}</div>
        </div>
        <div class="syns-block">
          <div class="row-label">SSC Synonyms</div>
          <div class="syns-list">
            <span class="syn primary">${d.syns[0]}</span>
            ${d.syns
              .slice(1)
              .map((s) => `<span class="syn">${s}</span>`)
              .join("")}
          </div>
        </div>
      </div>
    </div>
  `,
    )
    .join("");
}

function filterWords() {
  const q = document.getElementById("search").value.toLowerCase().trim();
  let data = words;
  if (currentFilter !== "all") {
    data = data.filter(
      (d) => d.exam && d.exam.toUpperCase().includes(currentFilter),
    );
  }
  if (q) {
    data = data.filter(
      (d) =>
        d.w.toLowerCase().includes(q) ||
        d.h.includes(q) ||
        d.syns.some((s) => s.toLowerCase().includes(q)) ||
        (d.exam && d.exam.toLowerCase().includes(q)),
    );
  }
  renderCards(data);
}

function setFilter(f, btn) {
  currentFilter = f;
  document
    .querySelectorAll(".filter-btn")
    .forEach((b) => b.classList.remove("active"));
  btn.classList.add("active");
  filterWords();
}

//       async function loadWords() {
//   const response = await fetch('words.json');
//   const words = await response.json();

//   renderCards(words);
// }

// loadWords();

renderCards(words);
